import Foundation

// Snapshot-harness fixtures for the tool-call digest: payload-shaped
// `actions_synopsis` objects generated by the Python reducer
// (`display_vocabulary.actions_synopsis`), so the gallery renders the daemon's
// own words for each state. Regenerate from Python; never hand-edit words.
enum ActionSynopsisSnapshotFixtures {
    static let byID: [String: ReceiptActionSynopsis] = {
        let json = #"""
{
 "absent": {
  "state": "capture_unknown",
  "headline": "capture coverage unknown",
  "integrity_detail": null,
  "metrics": [],
  "can_show_distribution": false,
  "capture_boundary": null,
  "stored_total": null,
  "categorized_total": 0,
  "tile": {
   "value": null,
   "absent": "capture coverage unknown",
   "qualifier": null
  }
 },
 "zero": {
  "state": "not_instrumented",
  "headline": "not instrumented",
  "integrity_detail": null,
  "metrics": [],
  "can_show_distribution": false,
  "capture_boundary": null,
  "stored_total": 0,
  "categorized_total": 0,
  "tile": {
   "value": null,
   "absent": "not instrumented",
   "qualifier": null
  }
 },
 "total-only": {
  "state": "total_only",
  "headline": "80 tool calls in stored total",
  "integrity_detail": "Tool-call type breakdown unavailable",
  "metrics": [],
  "can_show_distribution": false,
  "capture_boundary": "No ordered action ledger; captured tool-call counts cannot be linked to results or timing.",
  "stored_total": 80,
  "categorized_total": 0,
  "tile": {
   "value": "80",
   "absent": null,
   "qualifier": "Hook-captured"
  }
 },
 "exact": {
  "state": "exact",
  "headline": "80 tool calls captured",
  "integrity_detail": null,
  "metrics": [
   {
    "key": "read",
    "label": "Read",
    "detail": "File or context read tool calls",
    "count": 38
   },
   {
    "key": "edit",
    "label": "Edit",
    "detail": "Edit or write tool calls",
    "count": 7
   },
   {
    "key": "execute",
    "label": "Execute",
    "detail": "Command or process tool calls",
    "count": 24
   },
   {
    "key": "search",
    "label": "Search",
    "detail": "File or text search tool calls",
    "count": 11
   }
  ],
  "can_show_distribution": true,
  "capture_boundary": "No ordered action ledger; captured tool-call counts cannot be linked to results or timing.",
  "stored_total": 80,
  "categorized_total": 80,
  "tile": {
   "value": "80",
   "absent": null,
   "qualifier": "Hook-captured"
  }
 },
 "partial": {
  "state": "mismatch",
  "headline": "Tool-call totals conflict",
  "integrity_detail": "category counts sum to 7 · stored total is 10",
  "metrics": [
   {
    "key": "read",
    "label": "Read",
    "detail": "File or context read tool calls",
    "count": 7
   }
  ],
  "can_show_distribution": false,
  "capture_boundary": "No ordered action ledger; captured tool-call counts cannot be linked to results or timing.",
  "stored_total": 10,
  "categorized_total": 7,
  "tile": {
   "value": null,
   "absent": "tool-call totals conflict",
   "qualifier": null
  }
 },
 "mismatch": {
  "state": "mismatch",
  "headline": "Tool-call totals conflict",
  "integrity_detail": "category counts sum to 12 · stored total is 10",
  "metrics": [
   {
    "key": "read",
    "label": "Read",
    "detail": "File or context read tool calls",
    "count": 8
   },
   {
    "key": "edit",
    "label": "Edit",
    "detail": "Edit or write tool calls",
    "count": 4
   }
  ],
  "can_show_distribution": false,
  "capture_boundary": "No ordered action ledger; captured tool-call counts cannot be linked to results or timing.",
  "stored_total": 10,
  "categorized_total": 12,
  "tile": {
   "value": null,
   "absent": "tool-call totals conflict",
   "qualifier": null
  }
 },
 "invalid": {
  "state": "invalid",
  "headline": "Tool-call data incomplete",
  "integrity_detail": "1 invalid category was omitted · 8 valid tool calls remain categorized · stored total is 8",
  "metrics": [
   {
    "key": "read",
    "label": "Read",
    "detail": "File or context read tool calls",
    "count": 8
   }
  ],
  "can_show_distribution": false,
  "capture_boundary": "No ordered action ledger; captured tool-call counts cannot be linked to results or timing.",
  "stored_total": 8,
  "categorized_total": 8,
  "tile": {
   "value": null,
   "absent": "tool-call data incomplete",
   "qualifier": null
  }
 },
 "legacy": {
  "state": "total_unavailable",
  "headline": "5 categorized tool calls",
  "integrity_detail": "Stored tool-call total unavailable",
  "metrics": [
   {
    "key": "read",
    "label": "Read",
    "detail": "File or context read tool calls",
    "count": 3
   },
   {
    "key": "execute",
    "label": "Execute",
    "detail": "Command or process tool calls",
    "count": 2
   }
  ],
  "can_show_distribution": false,
  "capture_boundary": "No ordered action ledger; captured tool-call counts cannot be linked to results or timing.",
  "stored_total": null,
  "categorized_total": 5,
  "tile": {
   "value": "5",
   "absent": null,
   "qualifier": "categorized calls · Hook-captured"
  }
 },
 "high-cardinality": {
  "state": "unrecognized_categories",
  "headline": "65 tool calls captured",
  "integrity_detail": "40 unrecognized tool-call types were aggregated as Unrecognized types",
  "metrics": [
   {
    "key": "read",
    "label": "Read",
    "detail": "File or context read tool calls",
    "count": 20
   },
   {
    "key": "edit",
    "label": "Edit",
    "detail": "Edit or write tool calls",
    "count": 5
   },
   {
    "key": "__unknown_types__",
    "label": "Unrecognized types",
    "detail": "40 unrecognized categories",
    "count": 40
   }
  ],
  "can_show_distribution": false,
  "capture_boundary": "No ordered action ledger; captured tool-call counts cannot be linked to results or timing.",
  "stored_total": 65,
  "categorized_total": 65,
  "tile": {
   "value": "65",
   "absent": null,
   "qualifier": "Hook-captured · types changed"
  }
 },
 "max-taxonomy": {
  "state": "unrecognized_categories",
  "headline": "101 tool calls captured",
  "integrity_detail": "1 unrecognized tool-call type was aggregated as Unrecognized types",
  "metrics": [
   {
    "key": "read",
    "label": "Read",
    "detail": "File or context read tool calls",
    "count": 38
   },
   {
    "key": "edit",
    "label": "Edit",
    "detail": "Edit or write tool calls",
    "count": 7
   },
   {
    "key": "execute",
    "label": "Execute",
    "detail": "Command or process tool calls",
    "count": 24
   },
   {
    "key": "search",
    "label": "Search",
    "detail": "File or text search tool calls",
    "count": 11
   },
   {
    "key": "network",
    "label": "Network",
    "detail": "Network access tool calls",
    "count": 5
   },
   {
    "key": "agent",
    "label": "Agent",
    "detail": "Agent coordination tool calls",
    "count": 4
   },
   {
    "key": "plan",
    "label": "Plan",
    "detail": "Planning tool calls",
    "count": 3
   },
   {
    "key": "mcp",
    "label": "Connected tools",
    "detail": "Connected-tool calls",
    "count": 2
   },
   {
    "key": "other",
    "label": "Other",
    "detail": "Tool calls outside named categories",
    "count": 1
   },
   {
    "key": "__unknown_types__",
    "label": "Unrecognized types",
    "detail": "1 unrecognized category",
    "count": 6
   }
  ],
  "can_show_distribution": false,
  "capture_boundary": "No ordered action ledger; captured tool-call counts cannot be linked to results or timing.",
  "stored_total": 101,
  "categorized_total": 101,
  "tile": {
   "value": "101",
   "absent": null,
   "qualifier": "Hook-captured · types changed"
  }
 }
}
"""#
        return (try? JSONDecoder().decode([String: ReceiptActionSynopsis].self, from: Data(json.utf8))) ?? [:]
    }()

    static func synopsis(_ id: String) -> ReceiptActionSynopsis {
        byID[id] ?? ReceiptActionSynopsis(state: nil, headline: nil)
    }
}
